framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    default_locale: 'pl'
    enabled_locales: ['pl', 'en']
    set_content_language_from_locale: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    router:
        utf8: true

    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'pl'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
