parameters:
    app.article_export_directory: 'var/exports'
    app.article_import_directory: 'var/imports'
    app.media_directory: 'public/uploads/media'
    app.avatar_directory: 'public/uploads/avatars'
    app.media_orphan_ignored_filenames:
        - '.gitkeep'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: ../src/
        exclude:
            - ../src/DependencyInjection/
            - ../src/Entity/
            - ../src/Kernel.php

    App\Twig\AppGlobalsExtension:
        arguments:
            $appCache: '@cache.app'
            $appEnv: '%kernel.environment%'
