parameters:
    app.article_export_directory: 'var/exports'
    app.article_import_directory: 'var/imports'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: ../src/
        exclude:
            - ../src/DependencyInjection/
            - ../src/Entity/
            - ../src/Kernel.php

    App\Twig\AppGlobalsExtension:
        arguments:
            $appCache: '@cache.app'
            $appEnv: '%kernel.environment%'
