name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP with pre-release PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: bz2 bcmath ctype curl iconv exif fileinfo gd gmp hash json intl mbstring opcache pdo_sqlite readline session tokenizer xml xmlreader xmlwriter xsl zip
    
    - uses: actions/checkout@v4

    - name: Prepare Env File
      run: cp .env.template .env

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Install dependencies
      run: composer install --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer test
