name: PHP Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP with pre-release PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: bz2 bcmath ctype curl iconv exif fileinfo gd gmp hash json intl mbstring opcache pdo_sqlite readline session tokenizer xml xmlreader xmlwriter xsl zip
    
    - uses: actions/checkout@v5

    - name: Prepare Env File
      run: cp .env.template .env

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
      
    - name: Install dependencies
      run: composer install --no-progress

    - name: Run test suite
      run: composer test
